---
etcd_version: v3.5.9
etcd_data_dir: /data/etcd
etcd_listen_client_urls: http://0.0.0.0:2379
etcd_advertise_client_urls: "http://{{ ansible_hostname }}:2379"
etcd_listen_peer_urls: http://0.0.0.0:2380
etcd_initial_advertise_peer_urls: "http://{{ ansible_hostname }}:2380"
etcd_initial_cluster: "etcd-node1=http://etcd-node1:2380"
etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-cluster

postgres_version: 14
postgres_data_dir: /var/lib/postgresql/data
postgres_user: postgres
postgres_password: postgres
postgres_port: 5432

replicator_user: replicator
replicator_password: rep-pass

etcd_cluster: etcd-node1:2379
patroni_scope: postgres
patroni_watchdog_mode: off
