[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisor/supervisord.pid
nodaemon=true

[unix_http_server]
file=/var/run/supervisor/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/sshd.log
stdout_logfile=/var/log/supervisor/sshd.log

[program:patroni]
command=su - postgres -c "patroni /etc/patroni/patroni.yml"
autostart=false
autorestart=true
stderr_logfile=/var/log/supervisor/patroni.log
stdout_logfile=/var/log/supervisor/patroni.log
priority=999
